codecov:
  branch: master

coverage:
  status:
    project:
      default:
        target: 82.38
        threshold: '0.5%'
        if_not_found: success
        informational: false
        only_pulls: false
        if_ci_failed: error
    patch:
      default:
        threshold: '1%'
        if_not_found: success
        informational: false
        only_pulls: false
        if_ci_failed: error
