name: Prettier Check

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  prettier:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Verify Prettier formatting
        run: yarn prettier "**/*.{ts,tsx,css,graphql}" --check
