name: AI Code Reviewer

on:
  pull_request:
    types:
      - labeled
permissions: write-all
jobs:
  review:
    if: ${{ github.event.label.name == 'review' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: glific/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md, *.yml,  *.lock" # Optional: exclude patterns separated by commas
